### ISSUE TITLE
Javascript geselcteerde bericht uit als Javascript uit staat

### ISSUE THREAD

**Issue by driezie** [Seijno/the-web-is-for-everyone-interactive-functionality#6]
Als mijn javascript uit staat zie ik nogsteeds dat er iets staat over hoeveel ik er heb geselecteerd maar dit doet niks. Waarom doe je dit niet uit? Deze tekst kan je in je javascript inwerken

Dit is inderdaad een enhancement.

https://github.com/Seijno/the-web-is-for-everyone-interactive-functionality/blob/8f5d87b7488411d3fa6f2834d518fa3d7fab5cbd/views/index.ejs#L5

**Comment by Seijno** [comment]
opgelost door:

``` JS 
const appear = document.querySelector(".quantityChoice");
appear.style.display = 'block';

```
